version: '3'
# ==========================================
# ports configs:
# ==========================================
#   gateway - 80
#   other inf: 81**
#     keycloak - 8180
#   services: 80**
#     greeting-service - 8080
#     next-service - 8081

services:
  # ==========================================
  # Define a Keycloak service
  # ==========================================
  #keycloak-iam:
  #  ports:
  #    - "8180:8080"
  #  environment:
  #    KEYCLOAK_USER: "admin"
  #    KEYCLOAK_PASSWORD: "admin"
  #    DB_VENDOR: "h2"
  #  volumes: 
  #    - c:/dev/container-volumes/virtualparadigm.fintrader/keycloak:/tmp
  #  image: "jboss/keycloak"

  # ==========================================
  # Define a InfluxDB service
  # ==========================================
  influxdb:
    image: influxdb:1.3.5
    volumes:
      - c:/dev/container-volumes/virtualparadigm.fintrader.influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: "fintrader_instrument"
      INFLUXDB_USER: "test"
      INFLUXDB_USER_PASSWORD: "test"

  # ==========================================
  # Define a Chronograf service
  # ==========================================
  chronograf:
    image: chronograf:1.3.8
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    ports:
      - "8888:8888"
    links:
      - influxdb
      - kapacitor

  # ==========================================
  # Define a Kapacitor service
  # ==========================================
  kapacitor:
    image: kapacitor:1.3.3
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    links:
      - influxdb
    ports:
      - "9092:9092"

#  greeting-service:
#    ports:
#      - "8081:8080"
#    environment:
#      SOME_ENV: dev
#    image: "com.virtualparadigm.fintrader.app.reference.service/greeting-service"