version: '3'
# ports:
#   gateway - 80
#   other inf: 81**
#     keycloak - 8180
#   services: 80**
#     greeting-service - 8080
#     next-service - 8081

services:
  keycloak-iam:
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
      DB_VENDOR: "h2"
    volumes: 
      - c:\dev\container-volumes\virtualparadigm.fintrader.keycloak:/tmp
    image: "jboss/keycloak"
#  greeting-service:
#    ports:
#      - "8081:8080"
#    environment:
#      SOME_ENV: dev
#    image: "com.virtualparadigm.fintrader.app.reference.service/greeting-service"